### ISSUE TITLE
Error Uncaught TypeError: Cannot read properties of undefined (reading 'field')

### ISSUE THREAD

**Issue by bvitl** [h5p/h5p-php-library#136] opened 2022-10-10 06:07 UTC
When the language is different from English.
1. Select "Interactive Book"
2. Select "Interactive Video" 

In console:
Uncaught TypeError: Cannot read properties of undefined (reading 'field')
    at ns.updateCommonFieldsDefault (h5peditor.js?ver=1.15.4:268:60)
    at ns.updateCommonFieldsDefault (h5peditor.js?ver=1.15.4:266:10)
    at ns.updateCommonFieldsDefault (h5peditor.js?ver=1.15.4:266:10)
    at Object.success (h5peditor.js?ver=1.15.4:218:16)
    at c (jquery.js?ver=1.15.4:2:7857)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.15.4:2:8658)
    at k (jquery.js?ver=1.15.4:4:14015)
    at XMLHttpRequest.r (jquery.js?ver=1.15.4:4:18226)

After debugging:
In library Interactive Video in language there are not enough fields for which translation is not provided.

**Comment by fnoks** [comment] 2022-10-25 11:25
I believe this is a duplicate of https://github.com/h5p/h5p-interactive-video/issues/258

**Closed by fnoks** 2022-10-25 11:25 UTC
